layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Networking
    image_url: //conorwalsh.net/img/icons/cloud_networking.png

  - name: Internet of Things
    image_url: //conorwalsh.net/img/icons/iot-01.png

  - name: Telecommunications
    image_url: //conorwalsh.net/img/icons/telecomms-01.png
